---
title: "Tidytuesday_generic"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this #TidyTuesday I've tryied to reproduce the infografic created by AL-AHMADGAID B. ASAAD found in this post (https://alstatr.blogspot.com/2015/02/r-how-to-layout-and-design-infographic.html)[https://alstatr.blogspot.com/2015/02/r-how-to-layout-and-design-infographic.html]

# Libraries and settings
```{r}
rm(list = ls())
library(tidytuesdayR)
library(tidyverse)
library(pdftools)
library(extrafont)
library(ggsci)
library(grid)
library(useful)



#source("themes.R")

options(scipen = 999)
theme_set(theme_minimal())
loadfonts()

# dir.create("week_41")
# 
# path <- "C:/r_files/github/mytidytuesday/tidytuesday/week_41"
# setwd(path)
```

# Load data
```{r}
tuesdata <- tidytuesdayR::tt_load(2020, week = 41)
df.1 <- tuesdata$tournament
```

# Themes
```{r}
scale_color_g <- ggsci::pal_lancet()(9)

#scales::show_col(colors)
# Extend colors 
colors <- colorRampPalette(scale_color_g)

colors <- colors(15)

# Color vector
champs <- df.1 %>%
  count(tourney_finish, school, sort = T) %>% 
  filter(tourney_finish == "Champ") %>% 
  pull(school)

champs.colors <- set_names(colors)

# 
winners_vector1 <- gsub('\\"', "\\", paste(paste0(champs[c(1:8)], "\n"), collapse = '"'))
winners_vector2 <- gsub('\\"', "\\", paste(paste0(champs[c(9:15)], "\n"), collapse = '"'))
```

# tema 1
```{r}
kobe_theme <- function() {
  theme(
    plot.background = element_rect(fill = "#E2E2E3", colour = "#E2E2E3"),
    panel.background = element_rect(fill = "#E2E2E3", color = "transparent"),
    #panel.background = element_rect(color = "white"),
    axis.text = element_text(colour = "#E7A922"),
    plot.title = element_text(colour = "#552683", face = "bold", size = 18, vjust = 1),
    axis.title = element_text(colour = "#552683", face = "bold", size = 13),
    panel.grid.major.x = element_line(colour = "#E7A922"),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    strip.text = element_text( colour = "white"),
    strip.background = element_rect(fill = "#E7A922"),
    axis.ticks = element_line(colour = "#E7A922")
  )
}
```


# tema 2
```{r}
kobe_theme2 <- function() {
  theme(
    legend.position = "bottom", legend.title = element_text( colour = "#552683", size = 10),
    legend.background = element_rect(fill = "#E2E2E3"),
    legend.key = element_rect(fill = "#E2E2E3", colour = "#E2E2E3"),
    legend.text = element_text( colour = "#E7A922", size = 10),
    plot.background = element_rect(fill = "#E2E2E3", colour = "#E2E2E3"),
    panel.background = element_rect(fill = "#E2E2E3", color = "transparent"),
    #panel.background = element_rect(fill = "white"),
    axis.text = element_text(colour = "#E7A922"),
    plot.title = element_text(colour = "#552683", face = "bold", size = 18, vjust = 1),
    axis.title = element_text(colour = "#552683", face = "bold", size = 13),
    panel.grid.major.y = element_line(colour = "#E7A922"),
    panel.grid.minor.y = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    strip.text = element_text( colour = "white"),
    strip.background = element_rect(fill = "#E7A922"),
    axis.ticks = element_line(colour = "#E7A922")
  )
}
```


# Plot 1
```{r}
plot.1 <- df.1 %>%
  count(tourney_finish, school, sort = T) %>% 
  filter(tourney_finish == "Champ") %>% 
  mutate(school = fct_reorder(school, n)) %>% 
  ggplot(aes(x = n, y = school, fill = school)) +
  scale_fill_manual(values = champs.colors)+  
  geom_col()+
  theme(legend.position = "none")+
  labs(title = "Winners", x = "Number of times", y = "Schools")
```

# Plot 2
```{r}
#
# Tournament finish - The round of the final game for each team. OR=opening-round loss (1983 only); 1st=first-round loss; 2nd=second-round loss; RSF=loss in the Sweet 16; RF=loss in the Elite Eight; NSF=loss in the national semifinals; N2nd=national runner-up; Champ=national champions

levels <- c("1st", "2nd", "RSF", "RF", "NSF", "N2nd", "Champ")

plot.2 <- df.1 %>%
  add_count(tourney_finish, school, year, sort = T) %>% 
  filter(school %in% winners) %>% 
  mutate(school = fct_reorder(school, n)) %>% 
  mutate(tourney_finish = fct_relevel(tourney_finish, levels)) %>% 
  ggplot(aes(x = year, y = tourney_finish)) +
  geom_point(aes(group = school, 
                 color = school,
                 ), size = 5,  alpha = .9)+
  scale_color_manual(values = champs.colors)+
  labs(title = "Positions over time", y = "Tourney position", y = "years")+
  guides(colour = guide_legend(reverse=T))
```

# Plot 3
```{r}
winners_top_3 <- winners[c(1:3)]

plot.3 <- df.1 %>%
  add_count(tourney_finish, school, year, sort = T) %>% 
  filter(school %in% winners_top_3) %>% 
  mutate(school = fct_reorder(school, n)) %>% 
  mutate(tourney_finish = fct_relevel(tourney_finish, levels)) %>% 
  ggplot(aes(x = year, y = tourney_finish)) +
  geom_line(aes(group = school, 
                 color = school
                 ))+
  scale_color_manual(values = champs.colors)+
  facet_wrap(~school)+
  theme(legend.position = "bottom")+
  labs(title = "Top 3 winners", y = "Tourney position") +
  guides(colour = guide_legend(reverse=T))
```

# Plot theme 
```{r}
p1 <- plot.1 + kobe_theme()
p2 <- plot.2 + kobe_theme2()
p3 <- plot.3 + kobe_theme()
```


# Info
```{r}
pdf("Info_week_41.pdf", width = 10, height = 20)
grid.newpage() 
pushViewport(viewport(layout = grid.layout(4, 3)))
grid.rect(gp = gpar(fill = "#E2E2E3", col = "#E2E2E3"))
grid.text("NCAA Women's", y = unit(1, "npc"), x = unit(0.5, "npc"), vjust = 1, hjust = .5, gp = gpar( col = "#A9A8A7", cex = 8, alpha = 0.3))
grid.text("Basketball Tournament", y = unit(0.94, "npc"), gp = gpar(col = "#E7A922", cex = 4))
print(p3, vp = vplayout(4, 1:3))
print(p2, vp = vplayout(3, 1:3))
print(p1, vp = vplayout(2, 1:3))
grid.rect(gp = gpar(fill = "#E7A922", col = "#E7A922"), x = unit(0.5, "npc"), y = unit(0.82, "npc"), width = unit(1, "npc"), height = unit(0.11, "npc"))
grid.text("Schools", y = unit(0.82, "npc"), x = unit(0.5, "npc"), vjust = .5, hjust = .5, gp = gpar( col = "#CA8B01", cex = 13, alpha = 0.3))
grid.text("Winners", vjust = 0, hjust = 0, x = unit(0.01, "npc"), y = unit(0.86, "npc"), gp = gpar( col = "white", cex = 1.2))
grid.text(paste(winners_vector1, sep = "\n"), vjust = 0.2, hjust = 0, x = unit(0.01, "npc"), y = unit(0.79, "npc"), gp = gpar( col = "#552683", cex = 0.8))
grid.text(paste(winners_vector2, sep = "\n"), vjust = 0.2, hjust = 0, x = unit(0.15, "npc"), y = unit(0.79, "npc"), gp = gpar( col = "#552683", cex = 0.8))
dev.off()
```

```{r}
pdftools::pdf_convert("Info_week_41.pdf", 
                      filenames = "plot_week_41.png",
                      format = "png",
                      dpi = 600)
```

