---
title: "Tidytuesday_generic"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries and settings
```{r}
rm(list = ls())
library(tidytuesdayR)
library(tidyverse)
library(pdftools)
library(extrafont)
library(ggsci)
library(grid)
library(patchwork)

#source("themes.R")

options(scipen = 999)
theme_set(theme_minimal())
loadfonts()

# dir.create("week_43")
# 
# path <- "C:/r_files/github/mytidytuesday/tidytuesday/week_43"
# setwd(path)
```

# Load data
```{r}
tuesdata <- tidytuesdayR::tt_load(2020, week = 43)

df.1 <- tuesdata$beer_awards

caption_text <- paste0("Source: ", "Great American Beer Festival")
```

# Themes
```{r}
colors <- paste0("#",c("AF9500", "C9B037", "D7D7D7", "B4B4B4", "6A3805", "AD8A56"))

fonts <- extrafont::fonts()[102]
```

# Manipulation
```{r}
gold <- df.1 %>% 
  count(medal, category, beer_name) %>% 
  arrange(desc(n), medal, category, beer_name) %>% 
  filter(medal == "Gold") %>% 
  top_n(n, n = 10) %>% 
  mutate(beer_name = fct_reorder(beer_name, n)) %>% 
  uncount(n) %>% 
  mutate(category = str_remove(category, "or .*"))

silver <- df.1 %>% 
  count(medal, category, beer_name) %>% 
  arrange(desc(n), medal, category, beer_name) %>% 
  filter(medal == "Silver") %>%
  top_n(n, n = 10) %>% 
  mutate(beer_name = fct_reorder(beer_name, n)) %>% 
  uncount(n) %>% 
  mutate(category = str_remove(category, "or .*"))

bronze <- df.1 %>% 
  count(medal, category, beer_name) %>% 
  arrange(desc(n), medal, category, beer_name) %>% 
  filter(medal == "Bronze") %>%
  top_n(n, n = 2) %>% 
  mutate(beer_name = fct_reorder(beer_name, n)) %>% 
  uncount(n) %>% 
  mutate(category = str_remove(category, "or .*"))
  
```


```{r}
p1 <- gold %>% 
  ggplot(aes(x = beer_name, y = 1)) +
  scale_y_continuous(limits = c(-.3,.3))+
  geom_dotplot(stackdir = "center", fill = "#AF9500", color = alpha("white", .7), stroke = 1)+
  coord_flip()+
  geom_text(aes(x = beer_name, y = -.1, label = beer_name), color = "white", hjust = 1, fontface = "bold")+
  annotate(geom = "text", x = 16.5, y = -.1, label= "\nBeers", hjust = 1,  color = "white", size = 10, family = fonts)+
  geom_text(aes(x = beer_name, y = .1, label = category), color = "white", hjust = 0, fontface = "bold")+
  annotate(geom = "text", x = 16.5, y = .1, label= "\nCategory",hjust = 0, color = "white", size = 10, family = fonts)+
  theme(title = element_text(family = fonts),
        text = element_text(family = fonts),
        plot.title = element_text(color = "white", hjust = .5, size =20, face = "bold"),
        axis.text = element_blank(),
        axis.title = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_rect(fill = alpha(colors[2], .5), color = "transparent"),
        plot.background = element_rect(fill = colors[2],  color = "transparent"),
        plot.margin = unit(c(2,1,1,1,1), "cm"))+
  labs(title = "G O L D")
```


```{r}
p2 <- silver %>% 
  ggplot(aes(x = beer_name, y = 1)) +
  scale_y_continuous(limits = c(-.3,.3))+
  geom_dotplot(stackdir = "center", fill = colors[4], color = alpha("white", .7), stroke = 1)+
  coord_flip()+
  geom_text(aes(x = beer_name, y = -.1, label = beer_name), color = "white", hjust = 1, fontface = "bold")+
  annotate(geom = "text", x = 14, y = -.1, label= "\nBeers", hjust = 1,  color = "white", size = 10, family = fonts)+
  geom_text(aes(x = beer_name, y = .1, label = category), color = "white", hjust = 0, fontface = "bold")+
  annotate(geom = "text", x = 14, y = .1, label= "\nCategory",hjust = 0, color = "white", size = 10, family = fonts)+
  theme(title = element_text(family = fonts),
        text = element_text(family = fonts),
        plot.title = element_text(color = "white", hjust = .5, size = 20, face = "bold"),
        axis.text = element_blank(),
        axis.title = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_rect(fill = alpha(colors[3], .5), color = "transparent"),
        plot.background = element_rect(fill = colors[3],  color = "transparent"),
        plot.margin = unit(c(2,1,1,1,1), "cm"))+
  labs(title = "S I L V E R")
```

```{r}
p3 <- bronze %>% 
  ggplot(aes(x = beer_name, y = 1)) +
  geom_dotplot(stackdir = "center", fill = colors[5], color = alpha("white", .7), stroke = 1)+
  coord_flip(ylim = c(-.3,.3))+
  geom_text(aes(x = beer_name, y = -.1, label = beer_name), color = "white", hjust = 1, fontface = "bold")+
  annotate(geom = "text", x = 6, y = -.1, label= "\nBeers", hjust = 1,  color = "white", size = 10, family = fonts)+
  geom_text(aes(x = beer_name, y = .1, label = category), color = "white", hjust = 0, fontface = "bold")+
  annotate(geom = "text", x = 6, y = .1, label= "\nCategory",hjust = 0, color = "white", size = 10, family = fonts)+
  theme(title = element_text(family = fonts),
        text = element_text(family = fonts),
        plot.title = element_text(color = "white", hjust = .5, size = 20, face = "bold"),
        axis.text = element_blank(),
        axis.title = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_rect(fill = alpha(colors[6], .5), color = "transparent"),
        plot.background = element_rect(fill = colors[6],  color = "transparent"),
        plot.margin = unit(c(2,1,1,1,1), "cm"))+
  labs(title = "B R O N Z E")
```


```{r}
grid <- p1 + p2 + p3 

grid <- grid +
  plot_annotation(
  title = 'Great American Beer Festival',
  subtitle = 'Beer Awards - Winners of 3 or more medals',
  caption = caption_text,
  theme = theme(plot.title = element_text(vjust = 0, size = 40, hjust = .5, family = fonts, color = colors[1]),
                plot.subtitle = element_text(vjust = - 10, hjust = .5, color = colors[1], size = 16),
                plot.caption = element_text(color = colors[1]),
                plot.background = element_rect(fill = "#DCDCDC"))
)
```

```{r}
ggsave(plot = grid, filename = "week_43.png", width = 15,
       height = 7)
```

