---
title: "Tidytuesday_generic"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries and settings
```{r}
rm(list = ls())
library(tidytuesdayR)
library(tidyverse)
library(lubridate)
library(mdthemes)
library(scales)
library(pdftools)
library(extrafont)
library(ggsci)
library(grid)
library(patchwork)

#source("themes.R")

options(scipen = 999)
theme_set(theme_minimal())
loadfonts()

week <- paste0("week_", 52)

dir.create(week)

path <- paste0("C:/r_files/github/mytidytuesday/tidytuesday/", week)
setwd(path)
```

# Load data
```{r}
tuesdata <- tidytuesdayR::tt_load(2020, week = 52)

df.1 <- tuesdata$`big-mac`

caption_text <- paste0("Source: ", "TheEconomist | #TidyTuesdayProject")
```

# Manipulation
```{r}
df.2 <- df.1 %>%
  mutate(year = year(date)) %>% 
  group_by(name, year) %>% 
  summarise(median_country = mean(dollar_price)) %>% 
  ungroup() %>% 
  group_by(year) %>%   
  mutate(median_price = mean(median_country)) %>%
  ungroup() 
```

```{r}
plot <- ggplot(subset(df.2, name != "Brazil"),
       aes(x = year, y = median_country))+
  geom_line(aes(group = name), color = "gray")+
  scale_y_continuous(label = scales::dollar_format())+
  geom_line(data = subset(df.2, name == "Brazil"),
            size = 1.5, color = "yellow")+
  geom_text(aes(label = "Brazil", x = 2020, 
                y = 4.35), hjust = -0.5, color = "yellow")+
  geom_line(aes(x = year, y = median_price),
            color = "blue", size = 1.5)+
  geom_text(aes(label = "Average", x = 2020, 
                y = 3.6), hjust = -0.3, color = "blue")+
  coord_cartesian(clip = "off")+
  md_theme_economist()+
  theme(plot.margin = unit(c(.5,2,.5,.5), "cm"))+
  labs(title = "The Big Mac index in Brazil",
       subtitle = "Price of the Big Mac in Brazil and the average in the world over time",
       x = "",
       y = "",
       caption = caption_text)
```

```{r}
ggsave(plot = plot, filename = paste0("plot", week, ".png"), path = path)
```
