---
title: "Tidytuesday_generic"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries and settings
```{r}
rm(list = ls())
library(tidytuesdayR)
library(tidyverse)
library(pdftools)
library(ggridges)
library(extrafont)
#library(mdthemes)
# library(paletteer)
#source("themes.R")

options(scipen = 999)


#dir.create("week_39")

# path <- "C:/r_files/github/mytidytuesday/tidytuesday/week_39"
# setwd(path)
```

# Load data
```{r}
tuesdata <- tidytuesdayR::tt_load(2020, week = 39)
df.1 <- tuesdata$expeditions
```

# Manipulating
```{r}
df.2 <- df.1 %>% 
  drop_na() %>% 
  mutate(peak_name = fct_lump_n(peak_name, n = 10)) %>%
  filter(peak_name != "Other") %>%
  mutate(peak_name = fct_reorder(peak_name, year, .fun = sum))
```

# Colors and font
```{r}
back_color <- "#6490B3" #"#2163A0"

font_color <- "#DFDBD4"
palette <- paste0("#",c("774936","6e4230","653a2a","5c3324","532c1e","4a2419","411d13","38160d","2f0e07","260701"))

font <- extrafont::fonts()[114]
```

# Theme update
```{r}
theme_set(theme_minimal(base_size=15) +
            theme(
              title=element_text(family=font, 
                                 face = "bold", size=20),
              plot.subtitle=element_text(size = 14),
              panel.background=element_rect(fill = back_color, 
                                            color = back_color),
              plot.background=element_rect(fill = back_color),
              panel.grid=element_line(linetype="dashed"),
              text=element_text(color = font_color, face="bold.italic", family = font),
              axis.text=element_text(color = font_color),
              axis.text.y=element_blank(),
              plot.caption=element_text(size = 10),
            )
      )
```

# Plot
```{r}
plot <- df.2 %>% 
  #count(year, peak_name,name = "times") %>% 
  ggplot(aes(x = year, y = peak_name))+
  geom_density_ridges(aes(fill = peak_name), 
                      alpha = .7, color = font_color, show.legend=F)+
  scale_fill_manual(values = palette)+
  scale_x_continuous(limits=c(1973, 2022), breaks=seq(1980, 2020, 10))+
  geom_text(aes(x=1979, y = peak_name, 
                label = peak_name), vjust = -0.2, hjust = 1,
            color = font_color, size = 7, 
            fontface = "bold.italic", family = font)+
  labs(title = "Himalayan Climbing Expeditions",
       subtitle= "Ten most climbed peaks over time - Density by year",
       y = "", x = "",
       caption = "Source: The Himalayan Database \nTidyTuesday Project - week 39")
```

# run plot
```{r fig.width=15, fig.height=10}
X11(width=15, height=8)
plot
```


# Save plot
```{r}
# width = 17, height = 8.5
# width = 10, height = 5.7, device = cairo_pdf
# width = 19, height = 11, device = cairo_pdf
# width = 9, height = 14, device = cairo_pdf
# width = 15, height = 12
#Saving 5.27 x 3.93 in image == 13 x 9 centimetros


### Method 1
# Save to pdf
# ggsave(filename = "plot_week_39.pdf",
#        plot = plot, 
#        width = 15, height = 8, 
#        device = cairo_pdf) 
# 
# # Convert to png
# pdftools::pdf_convert("plot_week_39.pdf", 
#                       filenames = "plot_week_39.png",
#                       format = "png", 
#                       dpi = 250) #dpi 250-350
# 

### Method 2
ggsave(plot = plot, filename = "plot_week_39_2.png",
       width = 15, height = 8, dpi = 300)

```